title: Human Behavior Genetics, A Workbook
author: Jaime Derringer
email: jderr@illinois.edu
description: > # this means to ignore newlines until "twitter_username:"
  Open educational materials from PSYC 408 at University of Illinois Urbana-Champaign

# social links
# twitter_username: jekyllrb
github_username:  jaimederringer
google_scholar_username: DMSKadEAAAAJ
# rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
mastodon:
 - username: geneforanarchy
   instance: scholar.social
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: dark

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages: ['']

# Build settings
theme: minima
  
google_analytics: G-5ES13KP32S

plugins:
 - jekyll-feed
 - jekyll-seo-tag

# alt theme preference
# remote_theme: sighingnow/jekyll-gitbook

